### ISSUE TITLE
Multiple views not working in 3D MapView

### ISSUE THREAD

**Issue by akkravikumar** [wrld3d/android-api-samples#2]
Views are blinking continuously except last view.  Rest of others unable to views. Its blinking. Can you do resolve this issue.

**Comment by akkravikumar** [comment]
I tried this code also https://docs.eegeo.com/android/latest/docs/examples/position-multiple-views-on-map/

but it won't work. The view is displayed one at a time. cant view the multiple views.

should i add anything in xml for viewing multiple view.

**Comment by jlunderwood** [comment]
It looks like that example is out-of-date -- we're investigating and will update here as soon as possible

**Comment by akkravikumar** [comment]
Okay. Please let me know, once you are updated @jlunderwood @wrld-devops @wrld-teamcity

**Comment by jlunderwood** [comment]
Apologies for the confusion -- our documentation site was including an old example.  I've attached an updated example which should fix the flickering views.

We'll get the docs site fixed as soon as we can, but in the meantime I hope this helps.
[PositionCodeCreatedViewOnMapActivity.java.txt](https://github.com/wrld3d/android-api-samples/files/2262740/PositionCodeCreatedViewOnMapActivity.java.txt)

**Comment by akkravikumar** [comment]
Multiple views are displaying by using this class PositionCodeCreatedViewOnMapActivity.java.txt

But whenever I zoom in/out or move another place in the Map, the views(marker) of position are moving out from the exact location.

Okay let me check with latest version.

**Comment by akkravikumar** [comment]
Multiple views are displaying but whenever I zoom in/out or move to another place in the Map, the views(marker) of position are moving out from the exact location.
The Views are created by programmatically. Can you do help to resolve this. Video attached.

https://drive.google.com/file/d/1_BgBINI7t6A678UpNWOjO5GgX7QFC8kp/view?usp=sharing

@jlunderwood @wrld-devops

**Comment by jlunderwood** [comment]
It looks like your view may not be anchored using the most appropriate point for its shape.

In the example given above, the anchor point of the view (i.e. the view point that will be mapped to the geographic point given) is specified to be the center of the view, using the u,v offset (0.5f, 0.5f).  If you wish the anchor point to be at the bottom center of the view, you can specify (0.5f, 1.0f), or you can remove the use of ViewAnchor entirely and position the view directly yourself using the screenPoint returned.

**Comment by akkravikumar** [comment]
Same issue again. I tried this below code. Can you provide the code for what should i change here.

private class ViewAnchorAdapter implements OnPositionerChangedListener {
        private class ViewDetails {
            private View view;
            private PointF anchorUV;
        }

        private HashMap<Positioner, ViewDetails> m_views;

        ViewAnchorAdapter() {
            m_views = new HashMap<Positioner, ViewDetails>();
        }

        public void addView(@NonNull Positioner positioner, @NonNull View view, float u, float v) {
            ViewDetails viewDetails = new ViewDetails();
            viewDetails.view = view;
            viewDetails.anchorUV = new PointF(u, v);
            m_views.put(positioner, viewDetails);
        }

        @UiThread
        public void onPositionerChanged(Positioner positioner) {
            if (m_views.containsKey(positioner)) {
                ViewDetails viewDetails = m_views.get(positioner);
                if (positioner.isScreenPointProjectionDefined()) {
                    viewDetails.view.setVisibility(View.VISIBLE);
                    Point screenPoint = positioner.getScreenPointOrNull();
                    if (screenPoint != null) {
                        PointF anchorUV = new PointF(0.5f, 1.0f);
                        ViewAnchor.positionView(viewDetails.view, screenPoint, anchorUV);
                    }
                } else {
                    viewDetails.view.setVisibility(View.INVISIBLE);
                }
            }
        }
    }

@jbrownwrld @wrld-devops

**Comment by jlunderwood** [comment]
In general, the correct point will depend on the details of the view you are placing.  The code for ViewAnchor.positionView is simply 
`        view.setX(screenPoint.x - (view.getWidth()  * anchorUV.x));`
`        view.setY(screenPoint.y - (view.getHeight() * anchorUV.y));`

If you replace the call to `ViewAnchor.positionView` with
`view.setX(screenPoint.x);`
`view.setY(screenPoint.y);`
then you should see the view with its top left corner fixed at the geographical position specified.  You can then adjust the values passed to view.setX and view.setY as appropriate for your view.

Note that the view being placed must be a child of the map view, so you need to have the equivalent of `m_mapView.addView(imageView);` from the original example for your view.

**Comment by akkravikumar** [comment]
@jlunderwood Thanks. The problem got resolved. Cheers. @wrld-devops
