### ISSUE TITLE
Can we possible to add image to building walls

### ISSUE THREAD

**Issue by akkravikumar** [wrld3d/android-api-samples#3]
Hi @jbrownwrld & Team ,

Can we add image(like advertisement) to building side walls. If possible, can you help to improve posting images into building walls, 

Sample image attached.

<img width="368" alt="building_image" src="https://user-images.githubusercontent.com/597029/43899502-fefc412e-9b96-11e8-8ec6-72fd42fbc525.png">

**Comment by jlunderwood** [comment]
We don't support placement of views on buildings directly.

However, for a given building you can obtain its geometric information -- see https://wrld3d.com/android/latest/docs/examples/query-building-information/ for an example.
From this, you can determine some appropriate real-world points where you want to place the view.
You can then use Positioners to get the corresponding screen space points as the map view changes.

It will be up to you to calculate the appropriate transformation to apply to your view.
