### ISSUE TITLE
Does it support offline maps

### ISSUE THREAD

**Issue by binu8051** [wrld3d/android-api-samples#6]
Hi, nice library. Does this library support offline maps.
Thanks
Binu

**Comment by ghost** [comment]
Hi,

The app can cache data that has been already been streamed so it can be displayed when the device is offline.  We also have a precache API (https://www.wrld3d.com/android/latest/docs/examples/precaching-map-data/) so you can stream data before it is required.  However, it's not possible to download regions of data in advance and bundle them with an app.  Also, the app needs to contact WRLD when it first starts to authenticate.
